# Generated by Django 2.2.1 on 2019-05-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190525_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
